### ISSUE TITLE
Invalid issue passed as parameter of decorator is not reported

### ISSUE THREAD

**Issue by lukas-bednar** [rhevm-qe-automation/pytest_jira#25]
It might hide problems. see `test_jira_marker_bad_args` test it reproduce problem.

**Comment by vkondula** [comment]
#38 reports only markers, that does not match the pattern. (as in `test_jira_marker_bad_args` )
If it matches the pattern but the issue was not found, it's considered as open. Invalid marker could be caused by typo so should it rise an exception too?
On the other hand some text in docstring could match the pattern and not be intended as jira issue id.

**Comment by lukas-bednar** [comment]
@vkondula you are right . I would proceed with these steps:
* let the user to change pattern in config file
* let the user to set policy for these cases
  * strict / warn / open / ignore == error / print W / consider it as open / ignore (or something like that)
  * we can also add option to disable `__doc__` search

**Comment by lukas-bednar** [comment]
closed via #44
