### ISSUE TITLE
Enable plugin to fail gracefully on jira connection error 

### ISSUE THREAD

**Issue by liiight** [rhevm-qe-automation/pytest_jira#84]
Currently pytest crashes on jira connection error since it doesn't catch request exceptions. This has an undesirable effect of making builds that run pytest fail which cause false positives. 

I propose passing a flag that will enable either gracefully not load the plugin, or alternatively skip the test with a successful exit code. 

Thoughts?

**Comment by lukas-bednar** [comment]
In my opinion I think the best would skip loading plugin in that case.

but on other hand what if jira server go down during test execution?

I am not really confident with suggestions here, because since you expect some plugin to do some job for you and if it can not it should give you some feedback that something goes differently than expected ...

**Comment by lukas-bednar** [comment]
I would go with backward compatibility, so by default no 1 as a default, and I also think that no 3 & 4 find use case too.

**Comment by liiight** [comment]
Cool, I'll put up a PR

**Comment by lukas-bednar** [comment]
I think we are covered here, I am closing that.
If you miss something there feel free reopen it!
